"use strict";

console.time("test");

// Even Fibonacci numbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let total = 2,
    sum = 0,
    current = 2,
    prev = 1;

while (current < 4_000_000) {
    sum = prev + current;
    if (sum % 2 === 0) {
        total += sum;
    }
    prev = current;
    current = sum;
}
console.log(total);

console.timeEnd("test");
